### ISSUE TITLE
Interface in Array

### ISSUE THREAD

**Issue by erdemgonul** [AEB-labs/cruddl#189]
First of all thank you for that project,

I want to store a general class type which is called Children in an array and it can includes Screen or Test inside Module Type. Normally, graphql and some popular clients for db integrations supports those interface type but looks like not in cruddl. How can I achieve that purpose? Based on that feature,  we will use that project in a large-scale project. 

```
 interface Children{
      name: String
 }

 type Module @rootEntity {
      childrens : [Children] @relation(inverseOf: "parent")
 }
      
 type Screen implements Children @rootEntity{
      name : String
      //it will include some different variables
      parent: Module @relation
 }

 type Test implements Children @rootEntity{
      name : String
      //it will include some different variables
      parent: Module @relation
 }
```

**Comment by mfusser** [comment]
Hi,

sadly cruddl currently does not support such interface types and this will most likely not change in the near future.

A way to do this would be to use something like `type Children { screen: Screen, test: Test }` and then fill either field as neccessary. I think that is not really a pretty solution, but i can't think of a better one atm.
