### ISSUE TITLE
support arbitrary paging

### ISSUE THREAD

**Issue by pso-aeb** [AEB-labs/cruddl#24]
atm cursor-based paging is supported (`first` and `from`).

Would be great to also query an arbitrary page; something like:

```graphql
query {
  allOrders(filter: ..., orderBy: ..., start: 20, first: 10) {
    orderNumber
    _cursor
  }
}
```
to select 10 items, starting from the 20th item.

**Comment by Yogu** [comment]
I'd call it `skip` to be [compatible with prisma](https://www.prisma.io/docs/reference/prisma-api/queries-ahwee4zaey#pagination)
