### ISSUE TITLE
Sorting nested fields

### ISSUE THREAD

**Issue by samanthamcq** [AEB-labs/cruddl#292]
I would like to be able to sort nested fields. 

Here is an example of our schema:
```
type Product @childEntity {
  name: String
}

type Component @rootEntity {
  products: [Product]
}
```
I have a ui that list the components and would like to be able to sort the Component by product name. Is it possible to have an orderBy field like `products_product_name_asc`?

Thanks!

**Comment by Yogu** [comment]
You can sort by nested fields, but not across lists. If you had an entity extension or value object, you could use it in sorting:

```graphql
type Product @entityExtension {
  name: String
}

type Component @rootEntity {
  mainProduct: [Product]
}
```

```graphql
{
  allComponents(orderby: mainComponent_name_ASC) {
    ...
  }
}
```

How would you expect sorting to work with a list?

**Comment by Yogu** [comment]
Hi again,

closing this issue to get the list down a bit. Feel free to re-open when you want.
