### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Teoxoy** [AEB-labs/cruddl#80]
First of all I would like to thank you for the work you have done on this lib. I am quite excited that I found it, I was looking for ArangoDB support in prisma but it's not available.

Questions:

1. Is there any roadmap for the v1 release? - maybe I could help with something
2. Is there an ETA for #74? - ArangoSearch is a must have in my case
3. Is it possible to create the schema with [TypeGraphQL](https://typegraphql.ml/)? - I think it should be but not sure
4. What is the best way to use this lib? - Embedding it in a foxx service or just adding it on the server?

**Comment by Yogu** [comment]
Thanks for your interest!

> Is there any roadmap for the v1 release? - maybe I could help with something

We don't have planned something special for version 1.0 - we have already used it in production for a while. I guess we could just relese the next version as 1.0. I'd be quite liberal with small breaking changes however still as I don't think there is a large user base of cruddl at the moment that would be impacted.

> Is there an ETA for #74? - ArangoSearch is a must have in my case

It's going to be merged at some point within the next three months, probably earlier.

> Is it possible to create the schema with TypeGraphQL? - I think it should be but not sure

I'm not sure. I guess you could use TypeGraphQL's `buildTypeDefsAndResolvers` and just pass the `typeDefs` as one project source, but I haven't tried it. You won't be able to specify resolvers; cruddl handles them all by itself and it currently does not allow to add custom resolvers at the moment (it's planned for the future though, but you probably won't be able to just plug in TypeGraphQL then either).

> What is the best way to use this lib? - Embedding it in a foxx service or just adding it on the server?

cruddl should be run separately from ArangoDB in a standard node process. You can specify the URL and credentials for ArangoDB in the `ArangoDBAdapter`. cruddl is not compatible with foxx for a few reasons - it uses asynchronous request handling which foxx does not support, and it uses the HTTP API which would not really make sense within foxx.

**Comment by Teoxoy** [comment]
Thanks for the info!

Regarding #74, could I start to use it already on a custom cruddl build? Or is it still WIP? ArangoSearch is a must have in my case and waiting for 3 months for it to get merged would be too late.

**Comment by Teoxoy** [comment]
Actually, I might use Apollo Federation (stitching successor) for ArangoSearch queries or just make another ArangoDB connection trough ArangoJS to handle Search queries as you outlined here: https://github.com/AEB-labs/cruddl/issues/16#issuecomment-388786814 until #74 gets merged.

My comment above sounds like I want to rush the merge of #74 but that was not my intention. I was just looking for a workaround :)

**Comment by Teoxoy** [comment]
I have 2 more questions:
1. How is the runtime performance of the GraphQL queries being converted to AQL queries?
2. Is the AQL query memoized after cruddl has already converted a query from GraphQL?

**Comment by Yogu** [comment]
> Regarding #74, could I start to use it already on a custom cruddl build? Or is it still WIP? ArangoSearch is a must have in my case and waiting for 3 months for it to get merged would be too late.

There are still some open issues, but most of the featuers already work. The bigger concern would be that the API might change - e.g. it uses the working name `quickSearch` which we might want to change.

> Actually, I might use Apollo Federation (stitching successor) for ArangoSearch queries or just make another ArangoDB connection trough ArangoJS to handle Search queries as you outlined here: #16 (comment) until #74 gets merged.

That's great :)

> How is the runtime performance of the GraphQL queries being converted to AQL queries?

Obviously depends on the query complexity. In our testing environment where we have monitoring for this, the whole preparation (GraphQL -> AQL) takes 1ms on average (of a total query response average of 32ms).

> Is the AQL query memoized after cruddl has already converted a query from GraphQL?

No, this is currently not implemented. We didn't invest further in this because the preparation time only makes up a relatively small part of the total time, including plan optimization of ArangoDB (as long as ArangoDB does not support stored queries, see arangodb/arangodb#6999).

**Comment by Teoxoy** [comment]
Thanks for answering my questions!
I will keep this issue open a bit longer until I'm out of questions about cruddl :)

**Comment by Teoxoy** [comment]
Is there a way to specify the primary key options for a document collection?

>  keyOptions: additional options for key generation. If specified, then keyOptions should be a JSON array containing the following attributes:

You can find the rest [here ](https://www.arangodb.com/docs/3.4/http/collection-creating.html)

**Comment by Yogu** [comment]
> Is there a way to specify the primary key options for a document collection?

Currently there's no option for this. Out of curiosity, which options would you want to set? `padded` might be a good choice, especially for ArangoDB 3.5, where keys are no longer sorted lexicographically.

**Comment by Teoxoy** [comment]
Yeah, I was mainly looking for `padded`, they also say in the docs that `padded` is the best choice for RocksDB

**Comment by Yogu** [comment]
> Is there any roadmap for the v1 release? - maybe I could help with something

By the way - I decided to call the next release 1.0.0. There are still loads of features to be planned, but cruddl is stable, production-ready and offers enough functionality to cover many use cases.

**Comment by Teoxoy** [comment]
Awesome!
