### ISSUE TITLE
[BUG] Named query cache issue

### ISSUE THREAD

**Issue by Teoxoy** [AEB-labs/cruddl#82]
The result of a named query gets cached the first time it runs and the cache seems to ignore the variables being passed along with the query.

Subsequent runs of the same named query with different variables seem to return the cached result of the first query run.

I have tried to reproduce this issue [here](https://aeb-labs.github.io/cruddl) but I can't so this might not even be an issue with cruddl.

This is my current setup:
```js
import { Project, ArangoDBAdapter } from 'cruddl'
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory'
import { SchemaLink } from 'apollo-link-schema'
import env from '../utils/env'
import dbSchema from './schema.graphqls'

let dbClient: ApolloClient<unknown>

const initDBGQLClient = () => {
    const db = new ArangoDBAdapter({
        databaseName: env.DB_DATABASE,
        url: env.DB_URL,
        user: env.DB_USERNAME,
        password: env.DB_PASSWORD
    })

    const project = new Project({
        sources: [
            {
                name: 'schema.graphqls',
                body: dbSchema
            },
            {
                name: 'permission-profiles.json',
                body: JSON.stringify({
                    permissionProfiles: {
                        default: {
                            permissions: [
                                {
                                    roles: ['any'],
                                    access: 'readWrite'
                                }
                            ]
                        }
                    }
                })
            }
        ],
        getExecutionOptions: () => ({ authRoles: ['any'] })
    })

    // create missing collections then return client
    return db.updateSchema(project.getModel()).then(() => {
        dbClient = new ApolloClient({
            cache: new InMemoryCache(),
            link: new SchemaLink({ schema: project.createSchema(db) })
        })

        return dbClient
    })
}

export { initDBGQLClient, dbClient }
```

Sample query:
```js
dbClient.query({
    query: gql`
        query GET_USER_WITH_USERNAME($username: String!) {
            allUsers(filter: { username: $username }, first: 1) {
                id
                username
            }
        }
    `,
    variables: {
        username
    }
})
```

Sample query that works:
```js
dbClient.query({
    query: gql`
        query {
            allUsers(filter: { username: "${username}" }, first: 1) {
                id
                username
            }
        }
    `
})
```

As you can see, I am not using cruddl with a graphql server, instead I'm passing the schema directly to the apollo client using `apollo-link-schema`. Does cruddl only work with a graphql server? I don't see why this setup would cache a named query on the first run ignoring the variables.

I have asked about GraphQL to AQL query memoization and the answer (https://github.com/AEB-labs/cruddl/issues/80#issuecomment-504006547) was that it's not implemented but I'm not sure if cruddl performs any result caching.

**Comment by Yogu** [comment]
As I wrote cruddl does not implement caching. However, we assume that the document AST is different for each call, i.e., that the query is parsed freshly for each call. This is likely to cause your issue. You should be able to fix it by parsing and then re-printing (`parse(print(query))`), or by creating a new object for the query each time:

```
dbClient.query({
    query: Object.create(gql`
        query {
            allUsers(filter: { username: "${username}" }, first: 1) {
                id
                username
            }
        }
    `)
})
```

I'd consider this a bug in cruddl, but I don't really have an idea how to fix it. The problem is that we need to know what belongs to "one query call" so that we can convert the whole query into one AQL statement and not one AQL statement per top-level field.

**Comment by Teoxoy** [comment]
I see, I would consider it a bug too but I don't have a good solution for it. I guess you could call `Object.create` internally for each query but I don't think it would be an elegant solution.

I will leave this open, maybe you find a better way to fix it.

Thanks for the workaround though!

**Comment by Teoxoy** [comment]
Actually for anyone having this problem, `Object.create` doesn't work. I used the spread operator on the query (i.e. `{ ...IMPORTED_QUERY_NAME }`) you can also use `Object.assign`.

**Comment by Yogu** [comment]
> I see, I would consider it a bug too but I don't have a good solution for it. I guess you could call Object.create internally for each query but I don't think it would be an elegant solution.

I don't think I could call that internally - the point is that at no point, any code of cruddl is called exactly once for one query. Instead, graphql controls the whole execution and calls cruddl's resolver for each top-level field in the query.

> Actually for anyone having this problem, `Object.create` doesn't work. I used the spread operator on the query (i.e. `{ ...IMPORTED_QUERY_NAME }`) you can also use `Object.assign`.

Hm that's interesting, I wonder why. But good that you figured it out.

**Comment by Teoxoy** [comment]
> We could use the context, but that also isn't guaranteed to be unique for each call.

https://github.com/AEB-labs/cruddl/blob/95b36227736120bd330a1b3d34a4461c4cba4ca0/src/graphql/operation-based-resolvers.ts#L30

What do you think about using `opInfo` as the key for the cache? I think this combination should be unique.

**Comment by Yogu** [comment]
> What do you think about using `opInfo` as the key for the cache? I think this combination should be unique.

It would be *too* unique - the `GraphQLResolveInfo` object also contains e.g. the field name.

**Comment by Teoxoy** [comment]
Yeah, the cache would be useless then...

Idk what the solution would be then

**Comment by Teoxoy** [comment]
Looks like the `Object.assign` workaround is not a bulletproof fix...
Just found a case where it still returns the result of an old query.
I guess I will just have to stop using named queries for the time being...

**Comment by Yogu** [comment]
Are you sure this is related to named queries?

The problem might be in combination with your graphql client - maybe it does some kind of caching and e.g. re-uses the same DocumentNode in some cases?

**Comment by Teoxoy** [comment]
This issue happens only with named queries. If I use a "normal" query and pass in the variables in the `gql` template then everything works fine.

I have even looked at the source of `apollo-client` and also `apollo-link-schema` and they don't have any logic that would make the result of a query get cached. So I think this is an issue with cruddl. Have you tried to reproduce this issue? You guys are using cruddl in production, don't you guys use any named queries on the client apps?

**Comment by Teoxoy** [comment]
Ok, it seems "normal" queries behave the same but they didn't before. Not sure what the hell is happening tbh.

Now every time I call a query the result gets cached. So if I call a query that returns undefined then call a mutation to create the object in question - I still get undefined if I call the first query even though the object is in the db.

I have the `trace` option enabled for logging and I can see that on the second call of the query cruddl doesn't do anything.

So this issue might be with my setup and not with cruddl. But still, what's wrong with my setup? Instead of a client and a server I have only the `apollo-client` with `apollo-link-schema`. Is this an integration issue between `apollo-link-schema` and `cruddl`?

I don't want to have another express server running only for crudd. It would just add overhead for no reason. Using `apollo-client` with `apollo-link-schema` seemed like such an elegant solution.

Do you have any ideas how I could debug this further? Is there a way to see where the query result is coming from? It also doesn't help that I'm quite new to the graphql ecosystem...

**Comment by Teoxoy** [comment]
It looks like the issue was with `apollo-cache-inmemory`...

Creating the `apollo-client` with `fetchPolicy: 'no-cache'` fixes the issue
```js
const c = new ApolloClient({
    cache: new InMemoryCache(),
    link: new SchemaLink({ schema: project.createSchema(db) }),
    defaultOptions: {
        query: {
            fetchPolicy: 'no-cache'
        }
    }
})
```

It is obvious now but I have tried using `no-cache` before and it didn't work. It only worked when I restarted the app and not with rollup continuously watching the project.

Sorry for making this issue about cruddl but I was out of ideas and thought maybe cruddl has something to do with it.

Thanks for the help!

**Comment by Teoxoy** [comment]
Actually, even with `'no-cache'` the issue with the named query still persists if I don't use `Object.assign` on the query before calling it.

Tell me if I should reopen the issue.

**Comment by Yogu** [comment]
I think I know your problem, I needed to solve this when using cruddl in the front-end. _You should use a middleware so that the new document object is created *after* instead of before apollo's cache layer:

```typescript
        
```typescript
```typescript
    createLink(schema:GraphQLSchema): ApolloLink {
        const link = new AsyncSchemaLink({
            schema
        });

        // cruddl caches on the document node (arguably a bug) - this is to work around it
        const reparsingMiddleware = new ApolloLink((operation, forward: NextLink | undefined) => {
            if (!forward) {
                throw new Error(`reparsingMiddleware needs to be chained`);
            }
            return forward({
                ...operation,
                query: parse(print(operation.query))
            });
        });

        return concat(reparsingMiddleware, link);
    }
```

That's a snippet from our front-end development set up that works for us.

I guess intead of printing and re-parsing you can use `Object.assign`. I would also think that `Object.create` would work, but `Object.assign` creates a more "normal" object so I'd go with that.

I guess the confusion came from two things
- The inline query where you interpolated the value probably inlinled the variable into the query string, so it was different each run. That's not related to using anonymous / named operations.
- If you enable apollo caching, it will serialize the query to see if it matches the cache, and this will invalidate your attempt to create a new DocumentNode on each call.

**Comment by Teoxoy** [comment]
Yeah I had 2 issues at the same time, both about caching and thought they were related.

Thanks for the middleware example!
