### ISSUE TITLE
Cascading deletes

### ISSUE THREAD

**Issue by robross0606** [AEB-labs/cruddl#99]
Does cruddl have any existing capability or roadmap plans for supporting "cascading deletes" between root entities?  What happens currently with edge collections references documents when a vertex is deleted?

**Comment by Yogu** [comment]
> Does cruddl have any existing capability or roadmap plans for supporting "cascading deletes" between root entities?

It's been on our internal roadmap for a while, but without a date. I'm not sure yet if this should be a modelling feature (e.g. `someField: SomeType @relation(onDelete: CASCADE)`) or a feature on the mutation (`deleteSomething(id: "asf", cascades: { someField: true })`). What do you think?

**Comment by robross0606** [comment]
I think either way would be a phenomenal feature, and perhaps there's arguably room for both. The use cases are slightly different between the two approaches.  If I had to pick one, I would say it should be on the mutation since it allows more granular control over when/if you want cascades.  The other approach is a bit more formal and restrictive in that there could never be a case where you deleted one type without deleting the other.

**Comment by Yogu** [comment]
Ui I discovered an issue I can close as complete :) Cascading deletes have been supported since 2.1.0: https://github.com/AEB-labs/cruddl/releases/tag/v2.1.0
